export const DELETE_PET_SUCCESS = 'DELETE_PET_SUCCESS';
export const ADD_PET_SUCCESS = 'DELETE_PET_SUCCESS';
export const GET_PET_SUCCESS = 'GET_PET_SUCCESS';

export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';